"""
agent/email_sender.py

Converts the Markdown digest to a clean HTML email and sends it via SMTP.
Works with Gmail App Passwords, Mailgun SMTP, Postfix, etc.
"""

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import markdown  # pip install markdown

from config.settings import Settings

log = logging.getLogger(__name__)


def send_report(digest: str, today: str, settings: Settings) -> None:
    """Deliver via SMTP or leave the report as a CI artifact."""
    if settings.delivery_mode == "artifact":
        log.info("Artifact mode enabled; report is available in output/.")
        return
    if settings.delivery_mode != "smtp":
        raise ValueError("DELIVERY_MODE must be either 'artifact' or 'smtp'")
    if not all((settings.smtp_user, settings.smtp_password, settings.email_from, settings.email_to)):
        raise ValueError("SMTP mode requires SMTP_USER, SMTP_PASSWORD, EMAIL_FROM and EMAIL_TO")

    subject = f"{settings.email_subject_prefix} — {today}"
    html_body = _build_html(digest, today)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = settings.email_from
    msg["To"] = settings.email_to
    msg.attach(MIMEText(digest, "plain"))   # plain-text fallback
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP(settings.smtp_host, settings.smtp_port) as server:
            server.ehlo()
            server.starttls()
            server.login(settings.smtp_user, settings.smtp_password)
            server.sendmail(settings.email_from, settings.email_to, msg.as_string())
        log.info("Email sent to %s", settings.email_to)
    except Exception as exc:
        log.error("Failed to send email: %s", exc)
        raise


def send_digest_email(digest: str, today: str, settings: Settings) -> None:
    """Backward-compatible alias."""
    send_report(digest, today, settings)


def _build_html(digest: str, today: str) -> str:
    """Wrap the Markdown digest in a minimal, readable HTML email template."""
    body_html = markdown.markdown(
        digest,
        extensions=["extra", "nl2br"],
    )
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Daily Digest — {today}</title>
<style>
  body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
    background: #f5f5f0;
    margin: 0;
    padding: 24px 16px;
    color: #1a1a1a;
  }}
  .card {{
    background: #ffffff;
    max-width: 680px;
    margin: 0 auto;
    border-radius: 12px;
    border: 1px solid #e8e8e4;
    overflow: hidden;
  }}
  .header {{
    background: #1a1a1a;
    color: #ffffff;
    padding: 24px 32px 20px;
  }}
  .header h1 {{
    margin: 0 0 4px;
    font-size: 20px;
    font-weight: 500;
    letter-spacing: -0.3px;
  }}
  .header .date {{
    font-size: 13px;
    color: #999;
    margin: 0;
  }}
  .body {{
    padding: 28px 32px;
    line-height: 1.7;
    font-size: 15px;
  }}
  h2 {{
    font-size: 16px;
    font-weight: 500;
    border-bottom: 1px solid #ececec;
    padding-bottom: 8px;
    margin-top: 28px;
    color: #111;
  }}
  h3 {{
    font-size: 14px;
    font-weight: 500;
    color: #333;
    margin: 16px 0 6px;
  }}
  ul {{
    padding-left: 20px;
  }}
  li {{
    margin-bottom: 10px;
  }}
  a {{
    color: #0066cc;
    text-decoration: none;
  }}
  a:hover {{
    text-decoration: underline;
  }}
  blockquote {{
    border-left: 3px solid #ddd;
    margin: 12px 0;
    padding: 4px 16px;
    color: #555;
    font-style: italic;
  }}
  .footer {{
    padding: 16px 32px;
    font-size: 12px;
    color: #aaa;
    border-top: 1px solid #ececec;
    text-align: center;
  }}
</style>
</head>
<body>
  <div class="card">
    <div class="header">
      <h1>📰 Daily Digest</h1>
      <p class="date">{today} · Generated by Hermes Agent</p>
    </div>
    <div class="body">
      {body_html}
    </div>
    <div class="footer">
      Generated by Daily Digest Agent · Powered by Hermes + OpenRouter
    </div>
  </div>
</body>
</html>"""
